### ISSUE TITLE
Allow creation of Coverage reports

### ISSUE THREAD

**Issue by proffalken** [elmundio87/terraform_validate#22]
Currently, when running coverage reports on a repo using terraform_validate, coverage results are returned for the test framework itself, not the HCL for terraform to create it.

It would be great if we could run `nosetests --with-coverage` or similar and get a coverage report for our Terraform.

**Comment by elmundio87** [comment]
If anyone would like to implement this feature, I will be happy to merge a related PR!

**Comment by proffalken** [comment]
Superceded by other tools
